### ISSUE TITLE
[A18U] can't generate a world map

### ISSUE THREAD

**Issue by Glendening** [rheirman/RunAndGun#4]
Think run n gun is causing a hiccup with of all things world gen? At least that is what the troubleshooters on discord suggested. https://gist.github.com/HugsLibRecordKeeper/fd96e77be04238e9a6577d85c97de07e

**Comment by rheirman** [comment]
Thanks for reporting! I didn't notice that you posted an issue, so hence my late response, sorry for that. I'm working on an update today and I'll also address this.

**Comment by rheirman** [comment]
Ok I think it's solved in the new version I just released. Closing the issue
